name: Mirror SCAN (pull from Sheets)

on:
  workflow_dispatch: {}
  schedule:
    # Every 5 minutes during 09:00–16:00 America/Toronto (EDT ≈ UTC-4 → 13–20 UTC)
    - cron: "*/5 13-20 * * 1-5"

jobs:
  pull-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch SCAN CSV
        env:
          SCAN_URL: ${{ secrets.SCAN_URL }}
        run: |
          set -euo pipefail
          mkdir -p hot
          curl -fsSL --retry 3 --retry-delay 2 --max-time 45 "$SCAN_URL" -o hot/SCAN.csv.new

          # If existing file identical, bail early
          if [ -f hot/SCAN.csv ]; then
            if cmp -s hot/SCAN.csv.new hot/SCAN.csv; then
              echo "No change in SCAN.csv"
              exit 0
            fi
          fi

          mv -f hot/SCAN.csv.new hot/SCAN.csv
          echo "Updated hot/SCAN.csv"

      - name: Commit & push if changed
        run: |
          set -euo pipefail
          if git status --porcelain | grep -q .; then
            git config user.name  "sheets-mirror-bot"
            git config user.email "actions@users.noreply.github.com"
            git add hot/SCAN.csv
            git commit -m "mirror: refresh SCAN.csv (pull from Sheets)"
            git push
          else
            echo "Nothing to commit"
          fi
