name: secret-wiring-4d
on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify secrets resolve and CSVs are reachable (with URL sanitization)
        env:
          SCAN_URL:         ${{ secrets.SCAN_URL }}
          PRICES_URL:       ${{ secrets.PRICES_URL }}
          GLOBAL_CHECK_URL: ${{ secrets.GLOBAL_CHECK_URL }}
          HEALTH_URL:       ${{ secrets.HEALTH_URL }}
          GF_URL:           ${{ secrets.GF_URL }}
        shell: bash
        run: |
          set -euo pipefail

          sanitize() {
            # strip CR/LF and trim; percent-encode spaces and quotes
            printf '%s' "$1" | tr -d '\r\n' \
              | sed -e 's/^[[:space:]]\+//' -e 's/[[:space:]]\+$//' \
              | sed -e 's/ /%20/g' -e 's/"/%22/g'
          }

          test_csv () {
            local NAME="$1"; local RAW="$2"
            # ensure non-empty
            if [ -z "${RAW:-}" ]; then
              echo "::error ::$NAME secret is empty"; exit 1
            fi
            # sanitize
            local URL; URL="$(sanitize "$RAW")"

            echo "---- $NAME ----"
            # show status (do not print URL)
            status=$(curl -sI -L --globoff "$URL" | sed -n '1p' || true)
            echo "HTTP $status"

            # fetch first line of body
            head=$(curl -fsSL -L --globoff --retry 3 --retry-delay 2 --max-time 60 "$URL" | head -1 || true)
            if [ -z "$head" ]; then
              echo "::error ::$NAME returned empty
