name: secret-wiring-4d
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      SCAN_URL:         ${{ secrets.SCAN_URL }}
      PRICES_URL:       ${{ secrets.PRICES_URL }}
      GLOBAL_CHECK_URL: ${{ secrets.GLOBAL_CHECK_URL }}
      HEALTH_URL:       ${{ secrets.HEALTH_URL }}
      GF_URL:           ${{ secrets.GF_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify secrets resolve and CSVs are reachable
        shell: bash
        run: |
          set -euo pipefail

          # 1) ensure each secret is present (non-empty)
          for k in SCAN_URL PRICES_URL GLOBAL_CHECK_URL HEALTH_URL GF_URL; do
            v="${!k:-}"
            if [ -z "$v" ]; then
              echo "::error ::$k is MISSING or empty"; exit 1
            fi
            echo "::notice ::$k present (length ${#v})"
          done

          # 2) curl each URL: show HTTP status + first CSV header line
          test_csv () {
            NAME="$1"; URL="$2"
            echo "---- $NAME ----"
            status=$(curl -sI "$URL" | sed -n '1p' || true)
            echo "HTTP $status"
            head=$(curl -fsSL --retry 3 --retry-delay 2 --max-time 45 "$URL" | head -1 || true)
            if [ -z "$head" ]; then
              echo "::error ::$NAME returned empty body"; exit 1
            fi
            echo "Header: $head"
            echo
          }

          test_csv "SCAN"         "$SCAN_URL"
          test_csv "Prices"       "$PRICES_URL"
          test_csv "GLOBAL_CHECK" "$GLOBAL_CHECK_URL"
          test_csv "HEALTH"       "$HEALTH_URL"
          test_csv "__GF_FETCH__" "$GF_URL"

      - name: Commit sentinel (proves write permission)
        shell: bash
        run: |
          date -u +"%Y-%m-%dT%H:%MZ" > SECRET_WIRING_4D_OK
          git add SECRET_WIRING_4D_OK
          git -c user.name=github-actions -c user.email=actions@github.com commit -m "4D: secrets verified"
          git push || echo "Push blocked (branch protection?). OK if protected."
